# ADDITIONAL CONCLIQUE-BASED GIBBS SAMPLING STRATEGIES {#appendix-samplers}

The random sequence scan (RQGS) updates all concliques in a randomly selected order according to a fixed permutation probability. There are $Q!$ possible update orders. Let the $i^{th}$ update order be denoted $i(1), \dots, i(Q)$ and $q = \{q_1, \dots q_{Q!}\}$ be the permutation probabilities such that $\sum_{i = 1}^{Q!} q_i = 1$. The random scan (RSGS) randomly updates one conclique in each iteration while fixing the others according to a fixed component selection probability $p = \{p_1, \dots, p_Q\}$ where $p_i > 0$ and $\sum_{i = 1}^Q p_i = 1$ [@johnson2015geometric]. The algorithms are as follows.

**Conclique-based RQGS Algorithm**, Let $M \geq 1$ denote the number of complete Gibbs iterations:
\begin{enumerate}
\item Split locations into $Q \geq 2$ disjoint concliques, $\mathcal{C}_1,\ldots,\mathcal{C}_Q$.
\item Initialize the values of $\{Y^{(0)}(\boldsymbol s): \boldsymbol s \in \{\mathcal{C}_1, \dots, \mathcal{C}_Q\}\}$.
\item Draw a permutation of indices $\alpha$ according to the fixed permutation probabilities, $q = \{q_1, \dots q_{Q!}\}$.
\item For iteration $i = 1, \dots, M$,
  \begin{enumerate}
   \item Considering all locations $\boldsymbol s_j \in \mathcal{C}_{\alpha(1)}$, sample $\{Y^{(i)}(\boldsymbol s_j) :  \boldsymbol s_j \in \mathcal{C}_1 \}$ by independently drawing $Y^{(i)}(\boldsymbol s_j) \sim f_j(\cdot|\{Y^{(i-1)}(\boldsymbol s), \boldsymbol s \in \mathcal{N}_j\})$ from conditionals in (\ref{eqn:1}).
    \item Set $\ell =2$. Considering all locations $\boldsymbol s_j \in \mathcal{C}_\ell$, sample $\{Y^{(i)}(\boldsymbol s_j): \boldsymbol s_j \in \mathcal{C}_\ell\}$ by independently drawing $Y^{(i)}(\boldsymbol s_j) \sim f_j(\cdot|\boldsymbol y_{\alpha(\ell)}^{(i)}(\mathcal{N}_j))$ with conditioning observations $\boldsymbol y_{\alpha(\ell)}^{(i)}(\mathcal{N}_j) \equiv
\cup_{k=1}^{{\alpha(\ell)}-1} \{ Y^{(i)}(\boldsymbol s):\boldsymbol s \in \mathcal{N}_j \cap \mathcal{C}_k\} \bigcup \cup_{k={\alpha(\ell)}+1}^{Q} \{ Y^{(i-1)}(\boldsymbol s):\boldsymbol s \in \mathcal{N}_j \cap \mathcal{C}_k \}$, where the second set union is defined as empty if $\alpha(\ell)=Q$.  
    \item For $Q>2$, repeat step 2 for each $\ell=3,\ldots,Q$.
  \end{enumerate}
\end{enumerate}

**Conclique-based RSGS Algorithm**, Let $M \geq 1$ denote the number of complete Gibbs iterations:
\begin{enumerate}
\item Split locations into $Q \geq 2$ disjoint concliques, $\mathcal{C}_1,\ldots,\mathcal{C}_Q$.
\item Initialize the values of $\{Y^{(0)}(\boldsymbol s): \boldsymbol s \in \{\mathcal{C}_1, \dots, \mathcal{C}_Q\}\}$.
\item Draw an index $h$ according to the fixed component selection probability $p = \{p_1, \dots, p_Q\}$.
\item For iteration $i = 1, \dots, M$,
  \begin{enumerate}
   \item Considering all locations $\boldsymbol s_j \in \mathcal{C}_{h}$, sample $\{Y^{(i)}(\boldsymbol s_j) :  \boldsymbol s_j \in \mathcal{C}_h \}$ by independently drawing $Y^{(i)}(\boldsymbol s_j) \sim f_j(\cdot|\{Y^{(i-1)}(\boldsymbol s), \boldsymbol s \in \mathcal{N}_j\})$ from conditionals in (\ref{eqn:1}).
    \item For each $\boldsymbol s \in \mathcal{C}_j$ where $j \not= h$, $Y^{(i)}(\boldsymbol s) = Y^{(i - 1)}(\boldsymbol s)$.
  \end{enumerate}
\end{enumerate}

Each of the three Gibbs sampling techniques (including CGS) has a corresponding transition density $k(\boldsymbol x, \boldsymbol y)$, and one-step transition distribution $P(\boldsymbol x, A) =\int_A k(\boldsymbol x, \boldsymbol y)\mu(\boldsymbol y)$ based on an initialization $\boldsymbol x \in \mathcal{X}$. These densities are given in Table \ref{tab:densities}.

\begin{table}[H]
\centering
\caption{The transition densities for each of the three Gibbs sampling techniques, CGS, RQGS, and RSGS, where $\mathbb{I}(\cdot)$ is the indicator function and $\boldsymbol x_{-i} = \{\boldsymbol x_j, j \not=i\}$.}
\label{tab:densities}
\begin{tabular}{| l | l |}
\hline
Sampling Technique & Transition Density \\
\hline
CGS & $k_{CGS}(\boldsymbol x, \boldsymbol y) = f(\boldsymbol y_1|\boldsymbol x_2, \dots, \boldsymbol x_Q)f(\boldsymbol y_2 | \boldsymbol y_1, \boldsymbol x_3, \dots, \boldsymbol x_Q) \cdots f(\boldsymbol y_Q|\boldsymbol y_1, \dots, \boldsymbol y_{Q-1})$ \\
RQGS & $k_{RQGS}(\boldsymbol x, \boldsymbol y) = \sum\limits_{i = 1}^{Q!} q_i f(\boldsymbol y_{i(1)}|\boldsymbol x_{-i(1)})f(\boldsymbol y_{i(2)} | \boldsymbol y_{i(1)}, \boldsymbol x_{-(i(1), i(2))}) \cdots f(\boldsymbol y_{i(Q)}|\boldsymbol y_{-i(Q)})$ \\
RSGS & $k_{RSGS}(\boldsymbol x, \boldsymbol y) = \sum\limits_{i = 1}^Q p_i f(\boldsymbol y_i|\boldsymbol x_{-i}) \mathbb{I}(\boldsymbol x_{-i} = \boldsymbol y_{-i})$\\
\hline
\end{tabular}
\end{table}